CREATE TABLE IF NOT EXISTS ACCOUNT (ID BIGINT NOT NULL AUTO_INCREMENT, ACCOUNT_NUMBER VARCHAR(17) NOT NULL, BALANCE DECIMAL DEFAULT 0,
                                    PLAYER_ID BIGINT NOT NULL, STATUS SMALLINT, CREATED_DATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
                                    UPDATED_DATE_TIME TIMESTAMP, VERSION BIGINT NOT NULL , PRIMARY KEY (ID));

INSERT INTO ACCOUNT (ACCOUNT_NUMBER, PLAYER_ID, STATUS, VERSION, BALANCE)  values ('00000058398257466', 1, 1, 1, 1000);
INSERT INTO ACCOUNT (ACCOUNT_NUMBER, PLAYER_ID, STATUS, VERSION, BALANCE)  values ('00000058398257467', 2, 1, 1, 1000);
